//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace h24
{
    using System;
    using System.Collections.Generic;
    
    public partial class entries
    {
        public int id { get; set; }
        public string class_name { get; set; }
        public string team_name { get; set; }
        public string phone { get; set; }
        public Nullable<int> team_bib { get; set; }
        public string family1 { get; set; }
        public string given1 { get; set; }
        public string gender1 { get; set; }
        public string country1 { get; set; }
        public string birth_year1 { get; set; }
        public string si_chip1 { get; set; }
        public string family2 { get; set; }
        public string given2 { get; set; }
        public string gender2 { get; set; }
        public string country2 { get; set; }
        public string birth_year2 { get; set; }
        public string si_chip2 { get; set; }
        public string family3 { get; set; }
        public string given3 { get; set; }
        public string gender3 { get; set; }
        public string country3 { get; set; }
        public string birth_year3 { get; set; }
        public string si_chip3 { get; set; }
        public string family4 { get; set; }
        public string given4 { get; set; }
        public string gender4 { get; set; }
        public string country4 { get; set; }
        public string birth_year4 { get; set; }
        public string si_chip4 { get; set; }
        public string family5 { get; set; }
        public string given5 { get; set; }
        public string gender5 { get; set; }
        public string country5 { get; set; }
        public string birth_year5 { get; set; }
        public string si_chip5 { get; set; }
        public string family6 { get; set; }
        public string given6 { get; set; }
        public string gender6 { get; set; }
        public string country6 { get; set; }
        public string birth_year6 { get; set; }
        public string si_chip6 { get; set; }
        public string family7 { get; set; }
        public string given7 { get; set; }
        public string gender7 { get; set; }
        public string country7 { get; set; }
        public string birth_year7 { get; set; }
        public string si_chip7 { get; set; }
        public string family8 { get; set; }
        public string given8 { get; set; }
        public string gender8 { get; set; }
        public string country8 { get; set; }
        public string birth_year8 { get; set; }
        public string si_chip8 { get; set; }
        public string note { get; set; }
    }
}
